image: Visual Studio 2017

platform:
- x86
- x64

configuration:
  - Debug
  - Release
  
environment:
  matrix:
  - SHARED: OFF
    POSTFIXNAME: MT
    POSTVCPKGNAME: -static
        
    
matrix:
  fast_finish: true

install:  
  - mkdir build
  - cd build

build_script:
  - cd C:\projects\socket-lite\build\
  - if %platform%==x86 set generator=Visual Studio 15 2017
  - if %platform%==x64 set generator=Visual Studio 15 2017 Win64
  - cmd: echo %generator% %SHARED% %configuration% 
  - cmd: cmake -G"%generator%" -DBUILD_SHARED_LIBS=%SHARED% .. 
  - cmd: cmake --build .  --config %configuration%
  - ctest -C %configuration% -V 