image: Visual Studio 2019

platform:
- x86
- x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install:  
  - mkdir build
  - cd build

build_script:
  - cd C:\projects\socket-lite\build\
  - cmd: cmake -G"set generator=Visual Studio 16 2019" -A %platform% ..\test 
  - cmd: cmake --build .  --config %configuration%
  - ctest -C %configuration% -V 