image: Visual Studio 2017

platform:
- x86
- x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install:  
  - mkdir build
  - cd build

build_script:
  - cd C:\projects\socket-lite\build\
  - if %platform%==x86 set generator=Visual Studio 15 2017
  - if %platform%==x64 set generator=Visual Studio 15 2017 Win64
  - cmd: cmake -G"%generator%" ..\test 
  - cmd: cmake --build .  --config %configuration%
  - ctest -C %configuration% -V 