image: Visual Studio 2019

platform:
- x86
- x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install:  
  - mkdir build
  - cd build

build_script:
  - cd C:\projects\socket-lite\build\
  - if %platform%==x86 set plat=Win32
  - if %platform%==x64 set plat=x64
  - cmd: cmake -G"Visual Studio 16 2019" -A %plat% ..\test 
  - cmd: cmake --build .  --config %configuration%
  - ctest -C %configuration% -V 